/**
 * serverManager.js
 * Spawns and manages LinuxGSM processes, streams stdout/stderr over WebSocket.
 */

const { spawn, execFile } = require("child_process");
const path = require("path");
const fs = require("fs");
const db = require("./db");
const logger = require("./logger");
const config = require("./config");

// Track running child processes keyed by serverId
const runningProcs = new Map();

/**
 * Resolve the working directory for a server.
 * Each server lives in: <serversRoot>/<serverId>/
 */
function serverDir(server) {
  return path.join(config.serversRoot, server.id);
}

/**
 * Full path to the LGSM script for a server.
 */
function lgsmScript(server) {
  return path.join(serverDir(server), server.cmd);
}

/**
 * Ensure the server directory exists and the LGSM bootstrap script is present.
 */
async function ensureDir(server) {
  const dir = serverDir(server);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Spawn a shell command and stream its output.
 * @param {string}   cmd     - executable
 * @param {string[]} args    - arguments
 * @param {string}   cwd    - working directory
 * @param {Function} send   - WebSocket send helper
 * @param {string}   [serverId] - for process tracking
 * @returns {Promise<number>} - exit code
 */
function spawnAndStream(cmd, args, cwd, send, serverId) {
  return new Promise((resolve, reject) => {
    logger.info(`spawn: ${cmd} ${args.join(" ")} (cwd=${cwd})`);

    const proc = spawn(cmd, args, {
      cwd,
      env: { ...process.env, TERM: "xterm-256color" },
      shell: true,
    });

    if (serverId) runningProcs.set(serverId, proc);

    const emit = (text, streamType = "output") =>
      send({ type: "terminal", stream: streamType, text });

    proc.stdout.on("data", (d) => emit(d.toString()));
    proc.stderr.on("data", (d) => emit(d.toString(), "stderr"));

    proc.on("error", (err) => {
      emit(`Process error: ${err.message}`, "error");
      reject(err);
    });

    proc.on("close", (code) => {
      if (serverId) runningProcs.delete(serverId);
      resolve(code);
    });
  });
}

/**
 * Download the LinuxGSM installer and run auto-install for a server.
 */
async function install(server, send) {
  const dir = await ensureDir(server);
  const script = lgsmScript(server);

  db.updateServer(server.id, { status: "installing" });
  send({ type: "status", status: "installing", serverId: server.id });

  try {
    // Step 1 – Download linuxgsm.sh
    send({ type: "terminal", stream: "cmd", text: `wget -O ${server.cmd} https://linuxgsm.sh && chmod +x ${server.cmd}` });

    const dlCode = await spawnAndStream(
      "wget",
      ["-O", server.cmd, "https://linuxgsm.sh"],
      dir,
      send
    );
    if (dlCode !== 0) throw new Error(`wget exited with code ${dlCode}`);

    await spawnAndStream("chmod", ["+x", server.cmd], dir, send);

    // Step 2 – Run auto-install
    send({ type: "terminal", stream: "cmd", text: `bash ./${server.cmd} auto-install` });

    const installCode = await spawnAndStream(
      "bash",
      [script, "auto-install"],
      dir,
      send,
      server.id
    );
    if (installCode !== 0) throw new Error(`auto-install exited with code ${installCode}`);

    // Step 3 – Write lgsm/config
    await writeServerConfig(server, dir);

    // Step 4 – Start
    await _start(server, dir, send);

    db.updateServer(server.id, { status: "running" });
    send({ type: "status", status: "running", serverId: server.id });
    send({ type: "done", action: "install", success: true });
  } catch (err) {
    logger.error(`install failed (${server.id}):`, err.message);
    db.updateServer(server.id, { status: "error" });
    send({ type: "status", status: "error", serverId: server.id });
    send({ type: "done", action: "install", success: false, error: err.message });
  }
}

/**
 * Write LinuxGSM config file for the server.
 */
async function writeServerConfig(server, dir) {
  const cfgDir = path.join(dir, "lgsm", "config-lgsm", server.cmd);
  fs.mkdirSync(cfgDir, { recursive: true });

  const lines = [
    `## ${server.name} – generated by LinuxGSM Web GUI`,
    `servername="${server.name}"`,
    `port="${server.port}"`,
    `maxplayers="${server.maxPlayers}"`,
    server.password ? `serverpassword="${server.password}"` : "",
    `updateonstart="${server.autoUpdate ? "on" : "off"}"`,
    server.customFlags ? `startparameters="${server.customFlags}"` : "",
  ].filter(Boolean);

  fs.writeFileSync(path.join(cfgDir, `${server.cmd}.cfg`), lines.join("\n") + "\n");
}

/**
 * Internal: start the server process.
 */
async function _start(server, dir, send) {
  send({ type: "terminal", stream: "cmd", text: `./${server.cmd} start` });
  const code = await spawnAndStream("bash", [lgsmScript(server), "start"], dir, send, server.id);
  if (code !== 0) throw new Error(`start exited with code ${code}`);
}

async function start(server, send) {
  const dir = serverDir(server);
  if (!fs.existsSync(lgsmScript(server))) {
    return send({ type: "error", text: "Server not installed. Run install first." });
  }
  try {
    await _start(server, dir, send);
    db.updateServer(server.id, { status: "running" });
    send({ type: "status", status: "running", serverId: server.id });
    send({ type: "done", action: "start", success: true });
  } catch (err) {
    db.updateServer(server.id, { status: "error" });
    send({ type: "status", status: "error", serverId: server.id });
    send({ type: "done", action: "start", success: false, error: err.message });
  }
}

async function stop(server, send) {
  const dir = serverDir(server);
  const _send = send || (() => {});
  try {
    _send({ type: "terminal", stream: "cmd", text: `./${server.cmd} stop` });
    const code = await spawnAndStream("bash", [lgsmScript(server), "stop"], dir, _send, server.id);
    db.updateServer(server.id, { status: "stopped" });
    _send({ type: "status", status: "stopped", serverId: server.id });
    _send({ type: "done", action: "stop", success: code === 0 });
  } catch (err) {
    _send({ type: "done", action: "stop", success: false, error: err.message });
  }
}

async function restart(server, send) {
  try {
    send({ type: "terminal", stream: "cmd", text: `./${server.cmd} restart` });
    const dir = serverDir(server);
    await spawnAndStream("bash", [lgsmScript(server), "restart"], dir, send, server.id);
    db.updateServer(server.id, { status: "running" });
    send({ type: "status", status: "running", serverId: server.id });
    send({ type: "done", action: "restart", success: true });
  } catch (err) {
    send({ type: "done", action: "restart", success: false, error: err.message });
  }
}

async function update(server, send) {
  try {
    send({ type: "terminal", stream: "cmd", text: `./${server.cmd} update` });
    const dir = serverDir(server);
    db.updateServer(server.id, { status: "updating" });
    send({ type: "status", status: "updating", serverId: server.id });
    await spawnAndStream("bash", [lgsmScript(server), "update"], dir, send, server.id);
    db.updateServer(server.id, { status: "running" });
    send({ type: "status", status: "running", serverId: server.id });
    send({ type: "done", action: "update", success: true });
  } catch (err) {
    send({ type: "done", action: "update", success: false, error: err.message });
  }
}

async function backup(server, send) {
  try {
    send({ type: "terminal", stream: "cmd", text: `./${server.cmd} backup` });
    const dir = serverDir(server);
    await spawnAndStream("bash", [lgsmScript(server), "backup"], dir, send);
    send({ type: "done", action: "backup", success: true });
  } catch (err) {
    send({ type: "done", action: "backup", success: false, error: err.message });
  }
}

async function details(server, send) {
  try {
    send({ type: "terminal", stream: "cmd", text: `./${server.cmd} details` });
    const dir = serverDir(server);
    await spawnAndStream("bash", [lgsmScript(server), "details"], dir, send);
    send({ type: "done", action: "details", success: true });
  } catch (err) {
    send({ type: "done", action: "details", success: false, error: err.message });
  }
}

/**
 * Send a command to a running server's console (RCON or tmux send-keys).
 */
async function sendConsoleCommand(server, command, send) {
  if (!command) return send({ type: "error", text: "No command provided" });
  try {
    send({ type: "terminal", stream: "cmd", text: `./${server.cmd} send "${command}"` });
    const dir = serverDir(server);
    await spawnAndStream("bash", [lgsmScript(server), "send", command], dir, send);
    send({ type: "done", action: "console", success: true });
  } catch (err) {
    send({ type: "done", action: "console", success: false, error: err.message });
  }
}

module.exports = { install, start, stop, restart, update, backup, details, sendConsoleCommand };
